### ISSUE TITLE
Ability to disable/remove existing auto-installed plugins?

### ISSUE THREAD

**Issue by 3gmgithub** [PPCM/docker-glpi#13]
I cannot seem to disable the plugins that are auto-installed.
When I disable, after a docker restart they get activated again.
For now the only way I can find is the remove the permissions to the plugins.

Is there a better way to handle this?

**Comment by PPCM** [comment]
This is good idea, I keep it in mind

**Comment by 3gmgithub** [comment]
Thank you! You are the best!

**Comment by PPCM** [comment]
Variables were added
In that way, you can choose which plugin to install or activate
