### ISSUE TITLE
Memory errors in php-errors.log

### ISSUE THREAD

**Issue by 3gmgithub** [PPCM/docker-glpi#14]
I keep receiving: glpiphplog.CRITICAL:   *** PHP Error (1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 144793600 bytes) in /var/www/glpi/src/Toolbox.php at line 1085 

Now my queuednotifications keeps getting stuck.

Do you have any suggestions?

**Comment by PPCM** [comment]
Can you give some information, like the configuration of you host, how do you run your pods and log file?

**Comment by 3gmgithub** [comment]
Yes thank you.
Using Debian 12 4GB RAM
Using glpi-cron-daemon every two minutes

What log file do you want?

**Comment by 3gmgithub** [comment]
I was able to fix the issues with queuednotifications by deleting some from a few days ago. I am guessing one of them caused a problem in the queue.
However, this does not explain my memory size error, any suggestions?

**Comment by PPCM** [comment]
The response is somewhere in logs, it will tell what and why is the cause of the issue
logs are very important

**Comment by 3gmgithub** [comment]
```
glpi-cron-daemon  | crond: USER root pid  12 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  14 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 45056 bytes) in /var/www/glpi/src/Toolbox.php on line 1085
glpi-cron-daemon  | crond: USER root pid  16 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  18 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  20 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  22 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  24 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  59 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  69 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  71 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  73 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  75 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  77 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  87 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  89 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  91 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 45056 bytes) in /var/www/glpi/src/Toolbox.php on line 1085
glpi-cron-daemon  | crond: USER root pid  93 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  95 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  97 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid  99 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | crond: USER root pid 101 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
```

**Comment by PPCM** [comment]
The error comes from the creation of a huge image in png (this the corresponding line in Toolbox.php)
Do you have something like that?
Do you know what did you deleted from the queue?

**Comment by 3gmgithub** [comment]
We have our dashboard that creates the graphs...

**Comment by 3gmgithub** [comment]
I deleted emails from the queuednotification, but I am still receiving the memory errors in the logs so this appears to be unrelated.

**Comment by PPCM** [comment]
> We have our dashboard that creates the graphs...

If you are talking about statistics, they are generated by the browser in javascript, it is not that. It is something else
Once you find what it is, try to disable it

An other way, try to add more memory to your server

**Comment by 3gmgithub** [comment]
Is there any options to increase these PHP settings:

memory_limit="256M"
post_max_size="8M"
upload_max_filesize="2M"

The server never uses more than 50% of the 4GB RAM.

**Comment by 3gmgithub** [comment]
To troubleshoot I added a swapfile and turned zswap on.

**Comment by PPCM** [comment]
> Is there any options to increase these PHP settings:
> 
> memory_limit="256M" post_max_size="8M" upload_max_filesize="2M"
> 
> The server never uses more than 50% of the 4GB RAM.

I think you are using all the memory of your server, in particular if you are using swap memory
increasing memory_limit will have only one consequence -> decreasing performances of your GLPI

For exemple, in my case, I have to manage more than 200 computers + 450 screens + all their components + 75 printers + 15k softwares -> ~25 000 items
I manage my contracts, more than 100
Plus all associated files
Plus my tickets since 2 years -> ~5000
And I never reach the limit of my GLPI (and my hosts have 8Gb of RAM, shared by lot of pods ;-) )

So , I think you have two solution:
- Remove the element which consume so much memory (may be the best solution)
- Increase the real memory of your server (if you don't find the element)
But swap file is not so good in long terms

**Comment by 3gmgithub** [comment]
Thank you for the feedback.  I will look to see what may be consuming RAM. GLPI is the only thing running on this server.
