### ISSUE TITLE
10.0.17 still references php8.2 

### ISSUE THREAD

**Issue by flonou** [PPCM/docker-glpi#20]
Hi !
Thanks for the 10.0.17 version of the docker images.
I found however that they still reference php8.2 in some places and that the php executable name is now php83 instead of php (I created a symbolic link on my running container to fix this, I don't know how you would like to handle it)

https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron-daemon/glpi.cron#L1
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron-daemon/start_glpi-cron-daemon.sh#L18
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron-daemon/start_glpi-cron-daemon.sh#L21

https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron/start_glpi-cron.sh#L4
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron/start_glpi-cron.sh#L7
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-cron/start_glpi-cron.sh#L20

https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-server/start_glpi-server.sh#L106
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-server/start_glpi-server.sh#L109
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-server/start_glpi-server.sh#L112
https://github.com/PPCM/docker-glpi/blob/ad8e68c81ee06b34bc26cdf328b6731234090732/glpi-server/start_glpi-server.sh#L115

**Comment by 3gmgithub** [comment]
That happened to me too!

`glpi-server       | sed: /etc/php82/php.ini: No such file or directory
glpi-server       | sed: /etc/php82/php.ini: No such file or directory
glpi-server       | sed: /etc/php82/php.ini: No such file or directory
glpi-server       | sed: /etc/php82/php.ini: No such file or directory
glpi-server       | Current version : 10.0.17
glpi-server       | Docker version : 10.0.17`

**Comment by 3gmgithub** [comment]
Also had this issue:

```
glpi-cron-daemon  | crond: USER root pid  13 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | ash: /usr/bin/php: not found glpi-cron-daemon  | crond: USER root pid  13 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &
glpi-cron-daemon  | ash: /usr/bin/php: not found 
```

**Comment by 3gmgithub** [comment]
Fixed with symbolic links, but only temp fix as you know...

glpi-server
```
docker exec -it glpi-server ln -s /etc/php83 /etc/php82
```
glpi-cron-daemon
```
docker exec -it glpi-cron-daemon ln -s /usr/bin/php83 /usr/bin/php
```

**Comment by PPCM** [comment]
Hi!
Sorry guys for the mistake, I didn't pay attention to the error
A new release was published with fixes

Let me know if it works well for you

**Comment by 3gmgithub** [comment]
Looks like the what you did fixed the issue with server, but not the cron daemon...

```
glpi-cron-daemon  | crond: USER root pid  14 cmd su apache -s /bin/ash -c "cd /var/www/glpi; /usr/bin/php front/cron.php" &  glpi-cron-daemon  | ash: /usr/bin/php: not found
```

**Comment by PPCM** [comment]
A fix was posted to correct this issue
Sorry again
Hope this time it is fine... Let me know...

**Comment by 3gmgithub** [comment]
Looks fixed now!  Thanks!

**Comment by PPCM** [comment]
Great!
