### ISSUE TITLE
Don't require MYSQL_ROOT_PASSWORD

### ISSUE THREAD

**Issue by landure** [PPCM/docker-glpi#4]
First great job on this Docker image. It seems to be the best available for GLPI.

Could you not require MYSQL_ROOT_PASSWORD in container environment. I create the database manually, and my MariaDB server is shared with several other apps. It's also a security issue, since GLPI don't need root access to MariaDB.

**Comment by PPCM** [comment]
First, thanks, it's real pleasure

MYSQL_ROOT_PASSWORD is not mandatory if you create the user and the database in MariaDB by yourself
The first test in the script is to check if the user and the database exist, if not, MYSQL_ROOT_PASSWORD is required to create them

Did you test it without MYSQL_ROOT_PASSWORD and already created user and database?

**Comment by landure** [comment]
Hi, I beg to differ. See line 48 in `start_glpi-server.sh`:

```bash
if [ -z "${MYSQL_ROOT_PASSWORD}" ]
then
	echo "MYSQL_ROOT_PASSWORD must be set"
	exit 1
fi
```

**Comment by PPCM** [comment]
You are right, I forgot this
I will make some tests to enable this feature

**Comment by PPCM** [comment]
OK, it will be available in the next release
